<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentResults" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Compartilhado\" />
    <Folder Include="Compartilhado\Aplicacao\" />
    <Folder Include="Compartilhado\Apresentacao\" />
    <Folder Include="Compartilhado\Apresentacao\Extensions\" />
    <Folder Include="Compartilhado\Apresentacao\Views\" />
    <Folder Include="Compartilhado\Dominio\" />
    <Folder Include="Compartilhado\Infra\" />
    <Folder Include="Compartilhado\Infra\Arquivos\" />
    <Folder Include="ModuloCategoria\" />
    <Folder Include="ModuloCategoria\Aplicacao\" />
    <Folder Include="ModuloCategoria\Apresentacao\" />
    <Folder Include="ModuloCategoria\Apresentacao\Views\" />
    <Folder Include="ModuloCategoria\Dominio\" />
    <Folder Include="ModuloCategoria\Infra\" />
    <Folder Include="ModuloListaDeCompras\Apresentacao\Views\" />
    <Folder Include="ModuloListaDeCompras\Dominio\" />
    <Folder Include="ModuloListaDeCompras\Infra\" />
    <Folder Include="ModuloProduto\" />
    <Folder Include="ModuloProduto\Aplicacao\" />
    <Folder Include="ModuloProduto\Apresentacao\" />
    <Folder Include="ModuloProduto\Apresentacao\Views\" />
    <Folder Include="ModuloProduto\Dominio\" />
    <Folder Include="ModuloProduto\Infra\" />
  </ItemGroup>

</Project>
